version: '3.8'

services:
  wordpress:
    build: .
    container_name: vylp-wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      REDIS_URL: redis://redis:6379
      WP_ENVIRONMENT_TYPE: development
    volumes:
      - wordpress_data:/var/www/html
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - vylp-network

  mysql:
    image: mysql:8.0
    container_name: vylp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vylp-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: vylp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vylp-network
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vylp-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - vylp-network

volumes:
  wordpress_data:
  mysql_data:
  redis_data:

networks:
  vylp-network:
    driver: bridge